version: '3.9'
services:
  database:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
  backend:
    build: ./backend
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app